### ISSUE TITLE
Is there a build available?

### ISSUE THREAD

**Issue by Moult** [ADN-DevTech/aps-revit-ifc-exporter-appbundle#1]
G'day! We'd like to use this however on our corporate IT laptops we don't have a dev environment available to compile (and also compile multiple versions for each Revit version). Is it possible to provide builds that can be used out of the box?

**Comment by yiskang** [comment]
Hi @Moult,

If you're not talking about using CI build to automatically build this addin, you can find my compiled DLLs here.

https://github.com/yiskang/forge-revit-ifc-exporter-appbundle/tree/main/RevitIfcExportor/RevitIfcExportor.bundle/Contents

**Comment by Moult** [comment]
Nice! I know very little about how those DLLs link to different Revit versions - are they compatible with all Revit versions on the Forge DA API or do I need to select a particular Revit version?

**Comment by yiskang** [comment]
I haven't verified it yet, but Revit API I used in this repo exists in Revit 2021 and later versions. So, theoretically, this addin should work with Revit 2021 and later versions. (include Design Automation API for Revit)

But the better way is to compile this repo with Revit API DLLs from the corresponding Revit versions. I will try to figure out how to provide the DLLs build with the different Revit versions in the repo releases.

**Comment by Moult** [comment]
That would be very valuable! I will try to get this running over the next week at work!

**Comment by yiskang** [comment]
Hi @Moult,

You can find precompiled appbundles here, but please use that at your own risk, since I don't have enough code tests covered on this sample project.  

https://github.com/yiskang/aps-revit-ifc-exporter-appbundle/releases/tag/v1.0.0
