### ISSUE TITLE
Export without exportSettingName or by using one of the defaults

### ISSUE THREAD

**Issue by Moult** [ADN-DevTech/aps-revit-ifc-exporter-appbundle#5]
Is it possible to export using a custom export setting that does not yet have a name?

For example `exportSettingName` seems to be mandatory. However on a typical project, unless we ask them to set it up beforehand, there may not be any custom export settings already setup.

**Comment by yiskang** [comment]
Hi @Moult,

It's been added by this commit: https://github.com/yiskang/aps-revit-ifc-exporter-appbundle/commit/144138279904227f314bb3513b04150c8cf57931

- Update Activity config with the below
    ```json
       "userExportSettingsFile": {
            "verb": "get",
            "description": "JSON-based User-defined IFC export settings(configuration) file exported from Revit IFC addin",
            "localName": "userExportSettings.json"
        },
    ```
- Here is an example of using this feature: https://github.com/yiskang/aps-revit-ifc-exporter-appbundle#support-specifying-ifc-export-settings-on-the-fly-without-pre-saved-ones-in-rvt-file
